### ISSUE TITLE
Too many libs are exported somehow

### ISSUE THREAD

**Issue by Brunni** [piponazo/conan-opencv#1]
Hi,
I'm quite frustrated, as I was looking for one opencv conan library, which actually works. :)
This version here, is quite good as far as I see.

I used OpenCV with the default options and I get this error, when compiling my project on Ubuntu:
```
[ 89%] Linking CXX executable ../bin/myexecutable
/usr/bin/ld: cannot find -lopencv_objdetect
/usr/bin/ld: cannot find -lopencv_photo
/usr/bin/ld: cannot find -lopencv_shape
/usr/bin/ld: cannot find -lopencv_stitching
/usr/bin/ld: cannot find -lopencv_video
collect2: error: ld returned 1 exit status
```

I will now try building opencv from fresh, to see, if this helps.
EDIT: Issue still present.

**Comment by Brunni** [comment]
It also seems, that one of both sources of conanfile.py is outdated, as they don't match: Github and Conan:
https://www.conan.io/source/OpenCV/3.1.0-0/piponazo/testing

**Comment by piponazo** [comment]
Hi @Brunni, I am sorry for my long delay in the answer. I did not look after this repo for a long time. 

I will try to take a look to the problem you reported. Actually I will also update the library to the version 3.3.

Let me know if you would like to see the improvements in the version 3.1 or you are open to also update to 3.3 ;)

**Comment by piponazo** [comment]
Hi again. As you could have seen, things have changed a lot in conan since you wrote the comment. Anyways the error that you shared seems to be causde by a bad configuration of your project more than other thing. 

Let me know if I can help you somehow. I am closing this issue since it is not requesting anything specific about the conan recipe.
